# Generated by Django 4.0.6 on 2022-07-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000, verbose_name='Savol')),
                ('description', models.TextField(max_length=2000, verbose_name='Javob')),
            ],
            options={
                'verbose_name': 'Faq bo`limi',
                'verbose_name_plural': 'Faq bo`limi',
            },
        ),
    ]
