# Generated by Django 4.0.6 on 2022-07-08 18:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('sub_title', models.TextField(max_length=500)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Bizning Loyihalar',
                'verbose_name_plural': 'Bizning Loyihalar',
            },
        ),
    ]
