# Generated by Django 4.0.6 on 2022-07-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_projects_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='dfds', upload_to='images/'),
            preserve_default=False,
        ),
    ]
