# Generated by Django 4.0.6 on 2022-07-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_projects_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='link',
            new_name='slug',
        ),
    ]
