# Generated by Django 4.0.6 on 2022-07-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contact_create_date_contact_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Mijozlar bilan aloqa', 'verbose_name_plural': 'Mijozlar bilan aloqa'},
        ),
    ]
