# Generated by Django 4.0.6 on 2022-07-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ip',
            field=models.CharField(default='128', max_length=100),
            preserve_default=False,
        ),
    ]
