# Generated by Django 4.0.6 on 2022-07-10 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contact_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateField(auto_now=True, verbose_name='Xabar kelgan sana'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_time',
            field=models.TimeField(auto_now=True, verbose_name='Xabar kelgan vaqt'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=300, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ip',
            field=models.CharField(max_length=100, verbose_name='IP ADDRESS'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=300, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=3000, verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=300, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(max_length=600, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Javob'),
        ),
    ]
