# Generated by Django 4.0.6 on 2022-07-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_faq_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='telegram',
        ),
    ]
